### ISSUE TITLE
맥북프로 13인치 화면 최적화 이슈 

### ISSUE THREAD

**Issue by insub4067** [Async-Swift/SyncSwift2022#3]
<img width="1512" alt="스크린샷 2022-10-05 오후 3 54 21" src="https://user-images.githubusercontent.com/85481204/193998993-8ce626b0-c432-45cf-a5a2-d295c6b68aed.png">

- 위 화면은 맥북프로 13인치, 크롬에서 100% 로 본 화면 입니다
- 캡쳐에 보이다시피 하부 디자인이 씹히는 현상이 있습니다

**Comment by Blackraven93** [comment]
확인했습니다 rem 으로 수정하여 모바일과 웹페이지 레이아웃 수정했습니다!
