### ISSUE TITLE
아카데미 모니터 사이즈 최적화 이슈

### ISSUE THREAD

**Issue by insub4067** [Async-Swift/SyncSwift2022#6]
<img width="2560" alt="스크린샷 2022-10-06 오후 5 45 48" src="https://user-images.githubusercontent.com/85481204/194266116-c2a31f84-83e6-4f12-a8b3-9f3658904608.png">

맥북 13인치에서는 최적화가 된것을 확인하였습니다
하지만 모니터에 연결해서 확인해보니 비교적 하단에 패딩이 너무 많은 것이 아닌가 싶어 이슈 남깁니다
화면 비율에 맞게 패딩을 띄어서 레이아웃 / CSS 구성하면 어떨까 싶어 이슈 남깁니다

**Comment by Blackraven93** [comment]
형태를 보아하니 가장 최근에 배포된 형태가 아닌 듯 합니다!
혹시 최종 링크도 확인 부탁드리겠습니다!! [배포 링크](https://syncswift2022-daus2b1pu-asyncswift-korea.vercel.app/)
